### ISSUE TITLE
Keyboard emulation does not work on actual kiosk

### ISSUE THREAD

**Issue by JoshOldenburg** [RoboJackets/apiary-nfc-reader#6]
> `Xlib.error.DisplayNameError: Bad display name “”`

Additionally even if `-k` isn't specified, there are still errors.

**Comment by kberzinch** [comment]
If I had to guess, it's probably due to window manager differences between macos and ubuntu.

**Comment by JoshOldenburg** [comment]
Fixed, required the `DISPLAY` env variable to be set. See README.
